server:
  error:
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
        path: /
        max-age: 3650d #keep cookie long to prevent desync between cookie and localstorage.
      timeout: 3650d #keep cookie for 10 years.
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 116185664485434027643
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8080

